---
# handlers file for node-prerequisites

- name: enable docker
  service:
    name: docker
    enabled: yes

- name: restart docker
  service:
    name: docker
    state: restarted

- name: restart sshd
  service:
    name: sshd
    state: restarted
